name: 'Notify ServiceNow'
description: 'Post Deployment to ServiceNow CMDB'
inputs:
  debug:
    description: 'Debug log'
    required: false
    default: 'false'
  app-name:
    description: 'Application name'
    required: true
  cmdbid:
    description: 'The ServiceNow CMDB ID of the application'
    required: true
  api-key:
    description: 'The ServiceNow API key'
    required: true
  api-url:
    description: 'The ServiceNow API URL'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
